### ISSUE TITLE
Error when running the train command

### ISSUE THREAD

**Issue by willemarcel** [azavea/hot-osm-population#12]
```
+ set -e
+ BUCKET=hotosm-population
+ COMMAND=train
+ COUNTRY=zambia
+ WORLDPOP=s3://hotosm-population/WorldPop/ZMB_ppp_v2c_2020_UNadj.tif
+ [[ s3://hotosm-population/WorldPop/ZMB_ppp_v2c_2020_UNadj.tif == s3* ]]
+ WORLDPOP_URI=s3://hotosm-population/WorldPop/ZMB_ppp_v2c_2020_UNadj.tif
+ OSM_QA_URI=https://s3.amazonaws.com/mapbox/osm-qa-tiles-production/latest.country/zambia.mbtiles.gz
+ MODEL_URI=s3://hotosm-population/models/zambia-regression/
+ OUTPUT_URI=s3://hotosm-population/predict/zambia.json
+ TRAINING_URI=s3://hotosm-population/training/zambia.json
+ gunzip
+ curl -o - https://s3.amazonaws.com/mapbox/osm-qa-tiles-production/latest.country/zambia.mbtiles.gz
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed

0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0
4 91.6M 4 4401k 0 0 21.6M 0 0:00:04 --:--:-- 0:00:04 21.6M
44 91.6M 44 40.9M 0 0 34.1M 0 0:00:02 0:00:01 0:00:01 34.1M
96 91.6M 96 88.0M 0 0 39.9M 0 0:00:02 0:00:02 --:--:-- 39.9M
100 91.6M 100 91.6M 0 0 40.6M 0 0:00:02 0:00:02 --:--:-- 40.6M
+ JAR=/hot-osm-population-assembly.jar
+ shopt -s nocasematch
+ case ${COMMAND} in
+ aws s3 cp s3://hotosm-population/training/zambia.json /task/training-set.json
Completed 6.8 KiB/6.8 KiB (94.9 KiB/s) with 1 file(s) remaining
download: s3://hotosm-population/training/zambia.json to ./training-set.json
+ /opt/spark/bin/spark-submit --master 'local[*]' --driver-memory 7G --class com.azavea.hotosmpopulation.LabeledTrainApp /hot-osm-population-assembly.jar --country zambia --worldpop s3://hotosm-population/WorldPop/ZMB_ppp_v2c_2020_UNadj.tif --training /task/training-set.json --model /task/model --qatiles /task/zambia.mbtiles
Spark Configuration:
(spark.driver.memory,7G)
(spark.app.name,WorldPop-OSM-Train)
(spark.driver.host,172.31.4.116)
(spark.driver.maxResultSize,2G)
(spark.app.id,local-1543844579993)
(spark.ui.enabled,true)
(spark.master,local[*])
(spark.executor.id,driver)
(spark.driver.port,36047)
(spark.submit.deployMode,client)
(spark.jars,file:/hot-osm-population-assembly.jar)
Using 0 training polygons

[Stage 1:> (0 + 4) / 83]
[Stage 1:> (0 + 4) / 83]
[Stage 1:> (1 + 4) / 83]
[Stage 1:==> (3 + 4) / 83]
[Stage 1:==> (4 + 4) / 83]
[Stage 1:==> (4 + 4) / 83]
[Stage 1:===> (5 + 4) / 83]
[Stage 1:====> (6 + 4) / 83]
[Stage 1:====> (7 + 4) / 83]
[Stage 1:=====> (8 + 4) / 83]
[Stage 1:=====> (8 + 4) / 83]
[Stage 1:======> (9 + 4) / 83]
[Stage 1:======> (10 + 4) / 83]
[Stage 1:=======> (11 + 4) / 83]
[Stage 1:========> (12 + 4) / 83]
[Stage 1:========> (12 + 4) / 83]
[Stage 1:========> (13 + 4) / 83]
[Stage 1:=========> (14 + 4) / 83]
[Stage 1:==========> (15 + 4) / 83]
[Stage 1:==========> (16 + 4) / 83]
[Stage 1:==========> (16 + 4) / 83]
[Stage 1:===========> (17 + 4) / 83]
[Stage 1:============> (18 + 4) / 83]
[Stage 1:=============> (19 + 4) / 83]
[Stage 1:=============> (20 + 4) / 83]
[Stage 1:=============> (20 + 4) / 83]
[Stage 1:==============> (21 + 4) / 83]
[Stage 1:===============> (22 + 4) / 83]
[Stage 1:===============> (23 + 4) / 83]
[Stage 1:================> (24 + 4) / 83]
[Stage 1:================> (24 + 4) / 83]
[Stage 1:=================> (25 + 4) / 83]
[Stage 1:=================> (26 + 4) / 83]
[Stage 1:==================> (27 + 4) / 83]
[Stage 1:===================> (28 + 4) / 83]
[Stage 1:===================> (28 + 4) / 83]
[Stage 1:===================> (29 + 4) / 83]
[Stage 1:====================> (30 + 4) / 83]
[Stage 1:=====================> (31 + 4) / 83]
[Stage 1:=====================> (32 + 4) / 83]
[Stage 1:=====================> (32 + 4) / 83]
[Stage 1:======================> (33 + 4) / 83]
[Stage 1:=======================> (34 + 4) / 83]
[Stage 1:========================> (35 + 4) / 83]
[Stage 1:========================> (36 + 4) / 83]
[Stage 1:========================> (36 + 4) / 83]
[Stage 1:=========================> (37 + 4) / 83]
[Stage 1:==========================> (38 + 4) / 83]
[Stage 1:==========================> (39 + 4) / 83]
[Stage 1:===========================> (40 + 4) / 83]
[Stage 1:===========================> (40 + 4) / 83]
[Stage 1:============================> (41 + 4) / 83]
[Stage 1:============================> (42 + 4) / 83]
[Stage 1:=============================> (43 + 4) / 83]
[Stage 1:==============================> (44 + 4) / 83]
[Stage 1:==============================> (44 + 4) / 83]
[Stage 1:==============================> (45 + 4) / 83]
[Stage 1:===============================> (46 + 4) / 83]
[Stage 1:================================> (47 + 4) / 83]
[Stage 1:================================> (48 + 4) / 83]
[Stage 1:=================================> (49 + 4) / 83]
[Stage 1:==================================> (50 + 4) / 83]
[Stage 1:===================================> (51 + 4) / 83]
[Stage 1:===================================> (52 + 4) / 83]
[Stage 1:====================================> (53 + 4) / 83]
[Stage 1:=====================================> (54 + 4) / 83]
[Stage 1:=====================================> (55 + 4) / 83]
[Stage 1:======================================> (56 + 4) / 83]
[Stage 1:=======================================> (57 + 4) / 83]
[Stage 1:=======================================> (58 + 4) / 83]
[Stage 1:========================================> (59 + 4) / 83]
[Stage 1:=========================================> (60 + 4) / 83]
[Stage 1:=========================================> (61 + 4) / 83]
[Stage 1:==========================================> (62 + 4) / 83]
[Stage 1:===========================================> (63 + 4) / 83]
[Stage 1:===========================================> (64 + 4) / 83]
[Stage 1:============================================> (65 + 4) / 83]
[Stage 1:=============================================> (66 + 4) / 83]
[Stage 1:==============================================> (67 + 4) / 83]
[Stage 1:==============================================> (68 + 4) / 83]
[Stage 1:===============================================> (69 + 4) / 83]
[Stage 1:================================================> (70 + 4) / 83]
[Stage 1:================================================> (71 + 4) / 83]
[Stage 1:=================================================> (72 + 4) / 83]
[Stage 1:==================================================> (73 + 4) / 83]
[Stage 1:==================================================> (74 + 4) / 83]
[Stage 1:===================================================> (75 + 4) / 83]
[Stage 1:====================================================> (76 + 4) / 83]
[Stage 1:====================================================> (77 + 4) / 83]
[Stage 1:=====================================================> (78 + 4) / 83]
[Stage 1:======================================================> (79 + 4) / 83]
[Stage 1:======================================================> (80 + 3) / 83]
[Stage 1:=======================================================> (81 + 2) / 83]
[Stage 1:========================================================>(82 + 1) / 83]


[Stage 4:> (1 + 4) / 83]
[Stage 4:=> (2 + 4) / 83]
[Stage 4:==> (3 + 4) / 83]
[Stage 4:==> (4 + 4) / 83]
[Stage 4:===> (5 + 4) / 83]
[Stage 4:====> (6 + 4) / 83]
[Stage 4:====> (7 + 4) / 83]
[Stage 4:=====> (8 + 4) / 83]
[Stage 4:======> (9 + 4) / 83]
[Stage 4:======> (10 + 4) / 83]
[Stage 4:=======> (11 + 4) / 83]
[Stage 4:========> (12 + 4) / 83]
[Stage 4:========> (13 + 4) / 83]
[Stage 4:=========> (14 + 4) / 83]
[Stage 4:==========> (15 + 4) / 83]
[Stage 4:==========> (16 + 4) / 83]
[Stage 4:===========> (17 + 4) / 83]
[Stage 4:============> (18 + 4) / 83]
[Stage 4:=============> (19 + 4) / 83]
[Stage 4:=============> (20 + 4) / 83]
[Stage 4:==============> (21 + 4) / 83]
[Stage 4:===============> (22 + 4) / 83]
[Stage 4:===============> (23 + 4) / 83]
[Stage 4:================> (24 + 4) / 83]
[Stage 4:=================> (25 + 4) / 83]
[Stage 4:=================> (26 + 4) / 83]
[Stage 4:==================> (27 + 4) / 83]
[Stage 4:===================> (28 + 4) / 83]
[Stage 4:===================> (29 + 4) / 83]
[Stage 4:====================> (30 + 4) / 83]
[Stage 4:=====================> (31 + 4) / 83]
[Stage 4:=====================> (32 + 4) / 83]
[Stage 4:======================> (33 + 4) / 83]
[Stage 4:=======================> (34 + 4) / 83]
[Stage 4:========================> (35 + 4) / 83]
[Stage 4:========================> (36 + 4) / 83]
[Stage 4:=========================> (37 + 4) / 83]
[Stage 4:==========================> (38 + 4) / 83]
[Stage 4:==========================> (39 + 4) / 83]
[Stage 4:===========================> (40 + 4) / 83]
[Stage 4:============================> (41 + 4) / 83]
[Stage 4:============================> (42 + 4) / 83]
[Stage 4:=============================> (43 + 4) / 83]
[Stage 4:==============================> (44 + 4) / 83]
[Stage 4:==============================> (45 + 4) / 83]
[Stage 4:===============================> (46 + 4) / 83]
[Stage 4:================================> (47 + 4) / 83]
[Stage 4:================================> (48 + 4) / 83]
[Stage 4:=================================> (49 + 4) / 83]
[Stage 4:==================================> (50 + 4) / 83]
[Stage 4:===================================> (51 + 4) / 83]
[Stage 4:===================================> (52 + 4) / 83]
[Stage 4:====================================> (53 + 4) / 83]
[Stage 4:=====================================> (54 + 4) / 83]
[Stage 4:=====================================> (55 + 4) / 83]
[Stage 4:======================================> (56 + 4) / 83]
[Stage 4:=======================================> (57 + 4) / 83]
[Stage 4:=======================================> (58 + 4) / 83]
[Stage 4:========================================> (59 + 4) / 83]
[Stage 4:=========================================> (61 + 4) / 83]
[Stage 4:==========================================> (62 + 4) / 83]
[Stage 4:===========================================> (63 + 4) / 83]
[Stage 4:===========================================> (64 + 4) / 83]
[Stage 4:============================================> (65 + 4) / 83]
[Stage 4:=============================================> (66 + 4) / 83]
[Stage 4:==============================================> (67 + 4) / 83]
[Stage 4:==============================================> (68 + 4) / 83]
[Stage 4:===============================================> (69 + 4) / 83]18/12/03 14:40:24 ERROR Executor: Exception in task 72.0 in stage 4.0 (TID 157)
org.apache.spark.SparkException: Failed to execute user defined function(anonfun$2: (int, int) => rf_tile)
at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:395)
at org.apache.spark.sql.execution.columnar.InMemoryRelation$$anonfun$1$$anon$1.next(InMemoryRelation.scala:100)
at org.apache.spark.sql.execution.columnar.InMemoryRelation$$anonfun$1$$anon$1.next(InMemoryRelation.scala:92)
at org.apache.spark.storage.memory.MemoryStore.putIteratorAsBytes(MemoryStore.scala:372)
at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1055)
at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1029)
at org.apache.spark.storage.BlockManager.doPut(BlockManager.scala:969)
at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1029)
at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:760)
at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:334)
at org.apache.spark.rdd.RDD.iterator(RDD.scala:285)
at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
at org.apache.spark.scheduler.Task.run(Task.scala:108)
at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:338)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Rasterizer encountered an error: an odd number of X axis intersections encountered via a horizontal line across the raster at y = 54.
at geotrellis.raster.rasterize.polygon.PolygonRasterizer$.foreachCellByPolygon(PolygonRasterizer.scala:431)
at geotrellis.raster.rasterize.polygon.FractionalRasterizer$.foreachCellByPolygon(FractionalRasterizer.scala:185)
at com.azavea.hotosmpopulation.FootprintGenerator$$anonfun$apply$2.apply(FootprintGenerator.scala:105)
at com.azavea.hotosmpopulation.FootprintGenerator$$anonfun$apply$2.apply(FootprintGenerator.scala:103)
at scala.collection.immutable.Stream.foreach(Stream.scala:594)
at com.azavea.hotosmpopulation.FootprintGenerator.apply(FootprintGenerator.scala:103)
at com.azavea.hotosmpopulation.OSM$$anonfun$2.apply(OSM.scala:71)
at com.azavea.hotosmpopulation.OSM$$anonfun$2.apply(OSM.scala:70)
... 44 more
18/12/03 14:40:24 ERROR TaskSetManager: Task 72 in stage 4.0 failed 1 times; aborting job
Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Task 72 in stage 4.0 failed 1 times, most recent failure: Lost task 72.0 in stage 4.0 (TID 157, localhost, executor driver): org.apache.spark.SparkException: Failed to execute user defined function(anonfun$2: (int, int) => rf_tile)
at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:395)
at org.apache.spark.sql.execution.columnar.InMemoryRelation$$anonfun$1$$anon$1.next(InMemoryRelation.scala:100)
at org.apache.spark.sql.execution.columnar.InMemoryRelation$$anonfun$1$$anon$1.next(InMemoryRelation.scala:92)
at org.apache.spark.storage.memory.MemoryStore.putIteratorAsBytes(MemoryStore.scala:372)
at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1055)
at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1029)
at org.apache.spark.storage.BlockManager.doPut(BlockManager.scala:969)
at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1029)
at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:760)
at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:334)
at org.apache.spark.rdd.RDD.iterator(RDD.scala:285)
at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
at org.apache.spark.scheduler.Task.run(Task.scala:108)
at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:338)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Rasterizer encountered an error: an odd number of X axis intersections encountered via a horizontal line across the raster at y = 54.
at geotrellis.raster.rasterize.polygon.PolygonRasterizer$.foreachCellByPolygon(PolygonRasterizer.scala:431)
at geotrellis.raster.rasterize.polygon.FractionalRasterizer$.foreachCellByPolygon(FractionalRasterizer.scala:185)
at com.azavea.hotosmpopulation.FootprintGenerator$$anonfun$apply$2.apply(FootprintGenerator.scala:105)
at com.azavea.hotosmpopulation.FootprintGenerator$$anonfun$apply$2.apply(FootprintGenerator.scala:103)
at scala.collection.immutable.Stream.foreach(Stream.scala:594)
at com.azavea.hotosmpopulation.FootprintGenerator.apply(FootprintGenerator.scala:103)
at com.azavea.hotosmpopulation.OSM$$anonfun$2.apply(OSM.scala:71)
at com.azavea.hotosmpopulation.OSM$$anonfun$2.apply(OSM.scala:70)
... 44 more
Driver stacktrace:
at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1517)
at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1505)
at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1504)
at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1504)
at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:814)
at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:814)
at scala.Option.foreach(Option.scala:257)
at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:814)
at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1732)
at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1687)
at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1676)
at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:630)
at org.apache.spark.SparkContext.runJob(SparkContext.scala:2029)
at org.apache.spark.SparkContext.runJob(SparkContext.scala:2126)
at org.apache.spark.rdd.RDD$$anonfun$reduce$1.apply(RDD.scala:1026)
at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
at org.apache.spark.rdd.RDD.withScope(RDD.scala:362)
at org.apache.spark.rdd.RDD.reduce(RDD.scala:1008)
at org.apache.spark.rdd.RDD$$anonfun$treeAggregate$1.apply(RDD.scala:1151)
at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
at org.apache.spark.rdd.RDD.withScope(RDD.scala:362)
at org.apache.spark.rdd.RDD.treeAggregate(RDD.scala:1128)
at org.apache.spark.ml.optim.WeightedLeastSquares.fit(WeightedLeastSquares.scala:100)
at org.apache.spark.ml.regression.LinearRegression.train(LinearRegression.scala:220)
at org.apache.spark.ml.regression.LinearRegression.train(LinearRegression.scala:76)
at org.apache.spark.ml.Predictor.fit(Predictor.scala:118)
at com.azavea.hotosmpopulation.LabeledTrainApp$$anonfun$$lessinit$greater$1.apply(LabeledTrainApp.scala:109)
at com.azavea.hotosmpopulation.LabeledTrainApp$$anonfun$$lessinit$greater$1.apply(LabeledTrainApp.scala:51)
at cats.SemigroupalArityFunctions$$anonfun$map5$1.apply(SemigroupalArityFunctions.scala:75)
at cats.SemigroupalArityFunctions$$anonfun$map5$1.apply(SemigroupalArityFunctions.scala:75)
at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
at cats.data.Validated.ap(Validated.scala:172)
at cats.data.ValidatedApplicative.ap(Validated.scala:509)
at cats.data.ValidatedApplicative.ap(Validated.scala:502)
at cats.ComposedApply$$anonfun$ap$1$$anonfun$apply$1.apply(Composed.scala:33)
at cats.Monad$$anonfun$map$1.apply(Monad.scala:16)
at cats.instances.Function0Instances$$anon$1$$anonfun$flatMap$1.apply(function.scala:24)
at cats.instances.Function0Instances$$anon$1$$anonfun$flatMap$1.apply(function.scala:24)
at cats.instances.Function0Instances$$anon$1$$anonfun$flatMap$1.apply(function.scala:24)
at com.monovore.decline.Parser.com$monovore$decline$Parser$$evalResult(Parser.scala:26)
at com.monovore.decline.Parser.consumeAll(Parser.scala:91)
at com.monovore.decline.Parser.apply(Parser.scala:17)
at com.monovore.decline.Command.parse(opts.scala:17)
at com.monovore.decline.CommandApp.main(CommandApp.scala:48)
at com.azavea.hotosmpopulation.LabeledTrainApp.main(LabeledTrainApp.scala)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:775)
at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:119)
at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: org.apache.spark.SparkException: Failed to execute user defined function(anonfun$2: (int, int) => rf_tile)
at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:395)
at org.apache.spark.sql.execution.columnar.InMemoryRelation$$anonfun$1$$anon$1.next(InMemoryRelation.scala:100)
at org.apache.spark.sql.execution.columnar.InMemoryRelation$$anonfun$1$$anon$1.next(InMemoryRelation.scala:92)
at org.apache.spark.storage.memory.MemoryStore.putIteratorAsBytes(MemoryStore.scala:372)
at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1055)
at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1029)
at org.apache.spark.storage.BlockManager.doPut(BlockManager.scala:969)
at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1029)
at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:760)
at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:334)
at org.apache.spark.rdd.RDD.iterator(RDD.scala:285)
at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
at org.apache.spark.scheduler.Task.run(Task.scala:108)
at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:338)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Rasterizer encountered an error: an odd number of X axis intersections encountered via a horizontal line across the raster at y = 54.
at geotrellis.raster.rasterize.polygon.PolygonRasterizer$.foreachCellByPolygon(PolygonRasterizer.scala:431)
at geotrellis.raster.rasterize.polygon.FractionalRasterizer$.foreachCellByPolygon(FractionalRasterizer.scala:185)
at com.azavea.hotosmpopulation.FootprintGenerator$$anonfun$apply$2.apply(FootprintGenerator.scala:105)
at com.azavea.hotosmpopulation.FootprintGenerator$$anonfun$apply$2.apply(FootprintGenerator.scala:103)
at scala.collection.immutable.Stream.foreach(Stream.scala:594)
at com.azavea.hotosmpopulation.FootprintGenerator.apply(FootprintGenerator.scala:103)
at com.azavea.hotosmpopulation.OSM$$anonfun$2.apply(OSM.scala:71)
at com.azavea.hotosmpopulation.OSM$$anonfun$2.apply(OSM.scala:70)
... 44 more
```

**Comment by willemarcel** [comment]
Solved
